### ISSUE TITLE
ICAPS Updates

### ISSUE THREAD

**Issue by YIDING-CODER** [planimation/frontend#19]
Some new feature has been added to the system:
* User can upload PDDL plan rather than calling the planning solver
* Support function for the Plugin for PDDL Editor

**Comment by rakeshchoyal92** [comment]
Hi Ying,

I notice that auto build fails for this PR. 
On inspecting travis log, I found build script class and method name has been changed from `Buildscript.Build` to `buildscript.build`. There are two possible solution to this issue:

1. Stick to the name `Buildscript.Build`  
2. Amend dockerfile to reflect change in the class name. The docker file can be found at frontend/docker/release/Dockerfile. You simply need to change the line `ARG BUILD_SCRIPT=Buildscript.Build` => `ARG BUILD_SCRIPT= buildscript.build`

I hope this will resolve the issue with build pipeline.
