### ISSUE TITLE
CI CD Process test

### ISSUE THREAD

**Issue by YIDING-CODER** [planimation/frontend#32]
* Test the CI/CD Process

**Comment by rakeshchoyal92** [comment]
Hi Yi,

Please not that since the latest commit has failed; don't commit on top of it. I would recommend you to work on top of the commit  https://github.com/planimation/frontend/commit/cb30b0d6b4d8be66e4487479e2d0f1d5f40d562d since that was the latest successful built.

**Comment by YIDING-CODER** [comment]
Hi Rakesh,
Thank. I think it should work from this commit. Let me try.

**Comment by YIDING-CODER** [comment]
> Hi Yi,
> 
> Please not that since the latest commit has failed; don't commit on top of it. I would recommend you to work on top of the commit [cb30b0d](https://github.com/planimation/frontend/commit/cb30b0d6b4d8be66e4487479e2d0f1d5f40d562d) since that was the latest successful built.
