### ISSUE TITLE
Drag&Drop files

### ISSUE THREAD

**Issue by nirlipo** [planimation/frontend#45]
Usability would increase if we could drag&drop PDDL files and VFG files both in 

[planimation.planning.domains](https://planimation.planning.domains/) loading options

![image](https://user-images.githubusercontent.com/861782/77138070-84100c80-6ac4-11ea-9185-742a32042d3f.png)

For example, see screen below:

![image](https://user-images.githubusercontent.com/861782/77137977-267bc000-6ac4-11ea-895f-cfda0436f47b.png)

We also need to do the same for the editor.planning.domains. You can load a session and test the planimation through the plugin [planimation editor plugin](https://tinyurl.com/yxlt96fp)

We need to be able to drag and drop files into the left-hand bar instead of clicking file->load for each file required

![image](https://user-images.githubusercontent.com/861782/77138146-e537e000-6ac4-11ea-8792-875b88e89138.png)

**Comment by haz** [comment]
This would be great to have! Now, I'm not sure where you put the active area for dropping files (maybe just on the left pane? that would be the `#editor-tabs` div), but the code you'll likely want to mirror can be found in the [editor JS file](http://editor.planning.domains/js/main.js):

```javascript
function loadFromFile() {
    // Check for the various File API support.
    if (!(window.File && window.FileReader && window.FileList && window.Blob)) {
        window.toastr.error('The File APIs are not fully supported by your browser.');
        return;
    }

    //Retrieve the first (and only!) File from the FileList object
    var f = $('#inputfile')[0].files[0];

    // This check doesn't seem to work...
    /*if (!f.type.match('text.*')) {
        alert(f.name + " is not a valid text file: " + f.type);
        return;
    }*/

    if (f) {
        var r = new FileReader();
        r.onload = function(e) {
	        var contents = e.target.result;
	        createEditor();
	        $('#tab-' + window.current_editor).text(f.name);
	        var editor = window.ace.edit(window.current_editor);
	        editor.getSession().setValue(contents);
	        $('#loadButton').prop('disabled', true);
	        $('#inputfile').val('');
	        $('#loadModal').modal('toggle');
        }
        r.readAsText(f);
    } else {
        window.toastr.error("Failed to load file");
    }
}
```

If there's anything in there that doesn't make sense, just let me know.

**Comment by nirlipo** [comment]
Thanks @haz for the pointer. Is it possible to set the active area either in both the left pane and the main pane? The result should be the same, the files should appear on the left pane.

**Comment by haz** [comment]
Well one could question whether or not a drag over there shouldn't just put the file contents into the current pane. But perhaps it's simpler just to do the full screen one (side bar + main window). As a potential heads up, the editor part is a heavy beast with lots of functionality. You may find some conflicting JS quirks that prevent getting the drag&drop working there.

Re: Plugin
That's a good question. I think a natural way to approach this would be to start as a plugin, and then after stress testing it for a while we can include it into the core features. Another example of this path would be the save tabs feature -- it's enabled by default, but is core to sessions, etc. Likely will be included into the core JS code and removed as a plugin.

I'm open to suggestions though. Perhaps, just like Android development ;), keeping it modular is the better approach so you can update one part without affecting others. If this is the case, then the eventual feature of drag&drop would be an enabled-by-default plugin that's either dedicated to the feature or is a collection of features from UniMelb or something.

**Comment by hanbinl1** [comment]
@haz Thank you for the clarification. Also may I know where I can test the code? Since I couldn't find the editor files in this repo.

**Comment by haz** [comment]
If you write a plugin, you can load it from any location you like.

**Comment by nirlipo** [comment]
@hanbinl1 put your pluginFile.js file somewhere online so you can go to the editor.planning.domain, click in plugins -> "add URL" at the bottom -> "install plugin"

**Comment by hanbinl1** [comment]
@haz Hi Christian, the drag&drop function for editor.planimation is completed. 
The demo is shown below.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/38491392/82029863-efe4af00-96da-11ea-97f5-f5092546c13f.gif)
The code could be access here:
[https://hanbinl1.github.io/dragdrop-plugin.js](url)

**Comment by haz** [comment]
Thanks! So a few things.
- Can you run the code through an auto-formatter? 4-space indents, etc.
- The plugin should be in its own repo under https://github.com/AI-Planning . @nirlipo Should be able to hook you up, and you can see [this one](https://github.com/AI-Planning/planimation) as an example.
- I'm not super familiar with the implications of adding listeners the way you do, but if there's any way to _undo_ the initialization as part of `disable`, then that would be best. Specifically, you have 4 functions added as event listeners -- you don't need to cleanup/remove those functions, but remove the event listener for them restoring it to how it was prior to enabling. If this is possible, then I would recommend it.

**Comment by hanbinl1** [comment]
@haz Thanks for your advice!
- It is now formatted. 
- And for disable function, I removed the event listener. So it could be successfully disabled now. 
![ezgif com-gif-maker-3](https://user-images.githubusercontent.com/38491392/82118866-41656a80-97bd-11ea-87c7-d8c5847c0d38.gif)

**Comment by haz** [comment]
Awesome stuff! Able to put it in an `ai-planning` repo? That way, I can get it included with the official set of plugins.

**Comment by nirlipo** [comment]
Thanks @hanbinl1 !

I just created this repo: https://github.com/AI-Planning/drag-and-drop

Please push the plugin.js, and include in the readme the gif and anything you deem relevant.

See planimation plugin as an example: https://github.com/AI-Planning/planimation

**Comment by nirlipo** [comment]
@haz , code is available https://github.com/AI-Planning/drag-and-drop now. Let us know when it becomes live in the editor. I'd enable it by default.

**Comment by haz** [comment]
Had to change a few minor things (description, filenames), but we're all set to go. Cheers!

**Comment by hanbinl1** [comment]
Thanks a lot!

**Comment by nirlipo** [comment]
Drag-and-Drop has also been integrated in the frontend and passes all the tests. Thanks all!
