### ISSUE TITLE
Movie/GIF planimation

### ISSUE THREAD

**Issue by nirlipo** [planimation/frontend#46]
# Download planimations

We need to be able to export:

- [ ] movie 
- [ ] GIF animations
- [ ] Sequence of still PNG images

and define:

- [ ] a python API
- [ ] Investigate if it's possible to replace the front-end with [pddl-openai-gym](https://github.com/tomsilver/pddlgym), and connect the backend with openai. In a way the animation profile would automatically sinthesize the [python rendering](https://github.com/tomsilver/pddlgym/blob/master/pddlgym/rendering/blocks.py)

as an alternative method to generate/download planimations without using the UI (see below).

We currently can export a planimation into the Visualisation File Generator (VFG) format, see [documentation](https://planimation.github.io/documentation/VFG_guide/) for more details.

![image](https://user-images.githubusercontent.com/861782/77138277-8c1c7c00-6ac5-11ea-9539-bcfc4be1edd8.png)

If the download button is clicked, the backend generates a VFG file that can be loaded in the next session. 

# Python API 
Very much like the [http://api.planning.domains/](API for planning.domains), it would also be great to define a python API to query the backend using python, sending it the pddl files, and receiving back a (gist?) link with the images/gif/video

**Comment by nirlipo** [comment]
GIF and webm Format can be downloaded now.

Webm format is typically 3 times smaller than GIF and has better quality.

Below and example of a downloaded GIF

![planimation](https://user-images.githubusercontent.com/861782/84639694-15641300-af3c-11ea-8707-cd98ea9d35f7.gif)

Not sure if webm can be embedded in markdown as seen below:

![test-webm](http://techslides.com/demos/sample-videos/small.webm)

**Comment by Ojeechan** [comment]
Currently I'm planning about API design as the document below.
Information will be updated onwards.
[Proposal of GIF_Movie API (2).pdf](https://github.com/planimation/frontend/files/4849541/Proposal.of.GIF_Movie.API.2.pdf)

**Comment by nirlipo** [comment]
The proposed solution is great! thanks @Ojeechan !

It would great to also allow for step number 2 to be executed through another API that takes as input (domain, problem, animation) pddl files, and uses the backend to create the VFG file for the standalone unity.

This will decouple completely the use of the Unity front-end with the API to generate videos or screenshots.

**Comment by nirlipo** [comment]
The new JS front end doesn't allow yet to:
- export into movie (Mp4)
- export into a sequence of PNG
- Needs to add grey overlay over predicates which are part of the goal state
