### ISSUE TITLE
Unsuccessful deployment with latest dev version

### ISSUE THREAD

**Issue by ftdzh1994** [planimation/frontend#50]
There are several problem:

1. The local Dockerfile can build an image but the generated build folder is empty, so there is nothing but NGINX index page when open the localhost:8080.

2. The latest frontend images from Docker Hub has planimation pages and editor (not empty build foler). But it can't connect with server, causing error when trying to upload file to "build visualization from a problem".

**Comment by ftdzh1994** [comment]
1. This is cause by a typo in the "READ.ME" **Docker Build** part:
` export UNITY_LICENSE=LICENSE_FILE=Unity_lic.ulf` should be: `LICENSE_FILE=Unity_lic.ulf`

2. This problem results from #15 and related commit 2089582 as the backend URL hardcode is eliminated and related environment variable is not assigned.

**Comment by nirlipo** [comment]
Thanks @ftdzh1994 , please do a PR to close this issue.
